# Generated by Django 4.2.7 on 2025-12-26 15:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('product_type', models.CharField(choices=[('GAME', 'Game'), ('GIFTCARD', 'Gift Card')], max_length=20)),
                ('platform', models.CharField(choices=[('PC', 'PC'), ('PlayStation', 'PlayStation'), ('Xbox', 'Xbox'), ('Nintendo Switch', 'Nintendo Switch'), ('Mobile', 'Mobile'), ('Steam', 'Steam'), ('Epic Games', 'Epic Games'), ('Other', 'Other')], max_length=50)),
                ('region', models.CharField(default='Global', max_length=50)),
                ('category', models.CharField(choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('RPG', 'RPG'), ('Strategy', 'Strategy'), ('Sports', 'Sports'), ('Racing', 'Racing'), ('Simulation', 'Simulation'), ('Gift Card', 'Gift Card')], max_length=50)),
                ('images', models.JSONField(blank=True, default=list)),
                ('is_digital', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('featured', models.BooleanField(default=False)),
                ('discount', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'products',
                'indexes': [models.Index(fields=['product_type', 'platform', 'category'], name='products_product_12219d_idx'), models.Index(fields=['is_active', 'featured'], name='products_is_acti_44d253_idx')],
            },
        ),
    ]
